name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ dev ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend 
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Install dependencies
      run: npm install
      
    - name: Build App
      run: npm run build
      
    - name: Run ESLint
      run: npm run lint



      